spring.application.name=school-agenda-backend

# Para permitir referências circulares (NÃO RECOMENDADO, use apenas se necessário)
# spring.main.allow-circular-references=true

# IMPORTANTE: Efetuar a geração das chaves utiliando as instruções do arquivo "1. Gerando chaves VAPID - Informaçõe de Geração.txt"!
# Web Push VAPID Configuration - SIMPLIFIED IMPLEMENTATION
webpush.vapid.public-key=BFm3lGjAA4SQkkK_Kn0vHheIlx2lXsomgzgtGkt3DG4UBPP19aYRqIbl_N5fqG7f8vCKQ9YAX_TMYIufIfCWWAA
webpush.vapid.private-key=JbuhlMKsn7xVO5wpk6zFMBJHk101IBAsK-R3xlH5f6w
webpush.vapid.subject=mailto:admin@schoolagenda.com

# Database
spring.datasource.url=jdbc:h2:mem:schoolagenda
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# H2 Console
spring.h2.console.enabled=true

# Logging
logging.level.com.schoolagenda=INFO
