-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    push_subscription VARCHAR(2000)
);

-- User Roles Table (ElementCollection)
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Refresh Tokens Table
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Student Table
CREATE TABLE student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    profile_photo VARCHAR(255),
    registration_date TIMESTAMP(6),
    user_id BIGINT UNIQUE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Responsible Student Table (Relation between User and Student)
CREATE TABLE responsable_student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsable_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    FOREIGN KEY (responsable_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES student(id)
);

-- Announcements Table
CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    image_path VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    order_position INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    is_active BOOLEAN
);

-- Conversation Table
CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    attachment_path VARCHAR(255),
    sent_at TIMESTAMP(6) NOT NULL,
    read_status VARCHAR(50) NOT NULL,
    FOREIGN KEY (sender_id) REFERENCES users(id),
    FOREIGN KEY (recipient_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES student(id)
);

-- Events Table
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_date TIMESTAMP(6) NOT NULL,
    end_date TIMESTAMP(6) NOT NULL,
    color VARCHAR(7),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

-- Notifications Table
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    user_id BIGINT,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    type VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Push Subscriptions Table
CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL UNIQUE,
    p256dh VARCHAR(500) NOT NULL,
    auth VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Teacher Classes Table
CREATE TABLE teacher_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    class_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);
