-- ==============================================
-- TABELA: users (Usuários)
-- ==============================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    push_subscription VARCHAR(2000)
);

-- ==============================================
-- TABELA: user_roles (Papéis de Usuário)
-- ==============================================
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================
-- TABELA: refresh_tokens (Tokens de Atualização)
-- ============================================
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================
-- TABELA: school_classes (Turmas Escolares)
-- ============================================
CREATE TABLE school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    year INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    coordinator_id BIGINT,
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_coordinator_id
        FOREIGN KEY (coordinator_id)
            REFERENCES users(id)
            ON DELETE SET NULL
);

-- ============================================
-- TABELA: school_events (Eventos Escolares)
-- ============================================
CREATE TABLE school_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    all_day BOOLEAN DEFAULT FALSE,
    type VARCHAR(50) NOT NULL,
    school_class_id BIGINT,
    location VARCHAR(255),
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_event_class FOREIGN KEY (school_class_id) REFERENCES school_classes(id)
);

-- ============================================
-- TABELA: student (Alunos)
-- ============================================
CREATE TABLE student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    profile_photo VARCHAR(255),
    registration_date TIMESTAMP(6),
    global_average DECIMAL(5, 2) DEFAULT 0.00,
    user_id BIGINT UNIQUE,
    school_class_id BIGINT NOT NULL,
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (school_class_id) REFERENCES school_classes(id)
);

-- ============================================
-- TABELA: responsable_student (Responsáveis e Alunos)
-- ============================================
CREATE TABLE responsable_student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsable_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    FOREIGN KEY (responsable_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES student(id)
);

-- ============================================
-- TABELA: announcements (Anúncios)
-- ============================================
CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    image_path VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    order_position INTEGER NOT NULL,
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    is_active BOOLEAN
);

-- ============================================
-- TABELA: conversations (Conversas/Mensagens)
-- ============================================
CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    attachment_path VARCHAR(255),
    sent_at TIMESTAMP(6) NOT NULL,
    read_status VARCHAR(50) NOT NULL,
    FOREIGN KEY (sender_id) REFERENCES users(id),
    FOREIGN KEY (recipient_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES student(id)
);

-- ============================================
-- TABELA: events (Eventos)
-- ============================================
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_date TIMESTAMP(6) NOT NULL,
    end_date TIMESTAMP(6) NOT NULL,
    color VARCHAR(7),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

-- ============================================
-- TABELA: notifications (Notificações)
-- ============================================
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    user_id BIGINT,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    type VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================
-- TABELA: push_subscriptions (Assinaturas de Push)
-- ============================================
CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL UNIQUE,
    p256dh VARCHAR(500) NOT NULL,
    auth VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================
-- TABELA: messages (Mensagens)
-- ============================================
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    student_id BIGINT,
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    attachment_url TEXT,
    attachment_name VARCHAR(255),
--     read_at TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    archived_by_sender BOOLEAN DEFAULT FALSE,
    archived_by_recipient BOOLEAN DEFAULT FALSE,
    created_by VARCHAR(150),
    last_modified_by VARCHAR(150),
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- OU
--     created_at TIMESTAMPTZ NOW(),
--     updated_at TIMESTAMPTZ NOW(),

    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fk_message_recipient FOREIGN KEY (recipient_id) REFERENCES users(id),
    CONSTRAINT fk_message_student FOREIGN KEY (student_id) REFERENCES student(id)
);
/* Opcional: Índice para otimizar buscas se o volume de mensagens crescer */
CREATE INDEX idx_messages_attachment ON messages(attachment_url) WHERE attachment_url IS NOT NULL;

-- ============================================
-- TABELA: subjects (Disciplinas)
-- ============================================
CREATE TABLE subjects (
--    id BIGSERIAL PRIMARY KEY,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    school_year VARCHAR(10),
    teacher_user_id BIGINT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_subject_teacher
        FOREIGN KEY (teacher_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

-- Índices para subjects
CREATE INDEX idx_subjects_teacher ON subjects(teacher_user_id);
CREATE INDEX idx_subjects_active ON subjects(is_active);
CREATE INDEX idx_subjects_school_year ON subjects(school_year);

-- Trigger para updated_at
CREATE OR REPLACE FUNCTION update_subjects_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_subjects_updated_at
    BEFORE UPDATE ON subjects
    FOR EACH ROW
    EXECUTE FUNCTION update_subjects_updated_at();

-- ============================================
-- TABELA: evaluations (Avaliações)
-- ============================================
CREATE TABLE evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade DOUBLE PRECISION NOT NULL,
    title VARCHAR(255) NOT NULL,
    student_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_evaluation_student FOREIGN KEY (student_id) REFERENCES student(id),
    CONSTRAINT fk_evaluation_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- ============================================
-- TABELA: teacher_classes (Associação de Professores, Disciplinas e Turmas)
-- ============================================
CREATE TABLE teacher_classes (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     teacher_id BIGINT NOT NULL,
     subject_id BIGINT NOT NULL,
     school_class_id BIGINT NOT NULL, -- Substituído class_name por school_class_id
     created_by VARCHAR(150) DEFAULT NULL,
     last_modified_by VARCHAR(150) DEFAULT NULL,
     created_at TIMESTAMP DEFAULT NOW(),
     updated_at TIMESTAMP DEFAULT NOW(),

    -- Chaves Estrangeiras
     CONSTRAINT fk_teacher_classes_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
     CONSTRAINT fk_teacher_classes_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
     CONSTRAINT fk_teacher_classes_school_class FOREIGN KEY (school_class_id) REFERENCES school_classes(id),

    -- Índice para otimizar as consultas de segurança de Nível de Objeto
     CONSTRAINT uk_teacher_subject_class UNIQUE (teacher_id, subject_id, school_class_id)
);
-- Índice adicional para performance em buscas por professor/disciplina
CREATE INDEX idx_teacher_classes_lookup ON teacher_classes(teacher_id, subject_id);

-- CREATE TABLE teacher_classes (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     teacher_id BIGINT NOT NULL,
--     subject_id BIGINT NOT NULL,
--     class_name VARCHAR(100) NOT NULL,
--     created_by VARCHAR(150) DEFAULT NULL,
--     last_modified_by VARCHAR(150) DEFAULT NULL,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW(),
--     FOREIGN KEY (teacher_id) REFERENCES users(id),
--     FOREIGN KEY (subject_id) REFERENCES subjects(id)
-- );

-- Timetable Table
-- ============================================
-- TABELA: timetables (Horários/Aulas)
-- ============================================
CREATE TABLE timetables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_class_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
--     start_time TIME WITH TIME ZONE NOT NULL,
--     end_time TIME WITH TIME ZONE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_name VARCHAR(100),
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- ou
--     created_at TIMESTAMPTZ NOW(),
--     updated_at TIMESTAMPTZ NOW(),

    CONSTRAINT fk_timetable_teacher_class FOREIGN KEY (teacher_class_id) REFERENCES teacher_classes(id),
    -- Garante que o horário de término seja após o de início
    CONSTRAINT chk_timetable_times CHECK (end_time > start_time)
);

-- Índice para busca rápida de agenda por turma
CREATE INDEX idx_timetable_lookup ON timetables(teacher_class_id, day_of_week);

-- ============================================
-- TABELA: assessments (Avaliações/Atividades)
-- ============================================
CREATE TABLE assessments (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    subject_id BIGINT NOT NULL,
    created_by_user_id BIGINT,
    teacher_class_id BIGINT,
    due_date DATE,
    max_score NUMERIC(5,2) DEFAULT 10.00,
    weight DECIMAL(5,2) DEFAULT 1.0,
    is_published BOOLEAN DEFAULT FALSE,
    is_recovery BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_assessment_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_assessment_created_by
        FOREIGN KEY (created_by_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_assessment_teacher_class
        FOREIGN KEY (teacher_class_id)
        REFERENCES teacher_classes (id),

    CONSTRAINT chk_max_score_positive
        CHECK (max_score > 0)
);

-- Índices para assessments
-- (Opcional) Comentário na coluna para documentação do banco
COMMENT ON COLUMN assessments.weight IS 'Peso da avaliação para cálculo de média ponderada (ex: 1.0, 2.0, 3.0)';
CREATE INDEX idx_assessments_subject ON assessments(subject_id);
CREATE INDEX idx_assessments_created_by ON assessments(created_by_user_id);
CREATE INDEX idx_assessments_due_date ON assessments(due_date);
CREATE INDEX idx_assessments_published ON assessments(is_published);
-- Índice para performance, caso você precise filtrar avaliações por peso no futuro
CREATE INDEX idx_assessments_weight ON assessments(weight);

-- Trigger para updated_at
CREATE TRIGGER trigger_assessments_updated_at
    BEFORE UPDATE ON assessments
    FOR EACH ROW
    EXECUTE FUNCTION update_subjects_updated_at();

-- ============================================
-- TABELA: grades (Notas)
-- ============================================
CREATE TABLE grades (
    id BIGSERIAL PRIMARY KEY,
    assessment_id BIGINT NOT NULL,
    student_user_id BIGINT NOT NULL,
    score NUMERIC(5,2),
    max_score NUMERIC(5,2),
    feedback TEXT,
    graded_by_user_id BIGINT,
    graded_at TIMESTAMP,
    is_absent BOOLEAN DEFAULT FALSE,
    is_excused BOOLEAN DEFAULT FALSE,
    created_by VARCHAR(150) DEFAULT NULL,
    last_modified_by VARCHAR(150) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT uk_grade_assessment_student
        UNIQUE (assessment_id, student_user_id),

    CONSTRAINT fk_grade_assessment
        FOREIGN KEY (assessment_id)
        REFERENCES assessments(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_grade_student
        FOREIGN KEY (student_user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_grade_graded_by
        FOREIGN KEY (graded_by_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_score_range
        CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

-- Índices para grades
CREATE INDEX idx_grades_assessment ON grades(assessment_id);
CREATE INDEX idx_grades_student ON grades(student_user_id);
CREATE INDEX idx_grades_graded_by ON grades(graded_by_user_id);
CREATE INDEX idx_grades_score ON grades(score);

-- ============================================
-- TRIGGERS para updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para updated_at
CREATE TRIGGER trigger_grades_updated_at
    BEFORE UPDATE ON grades
    FOR EACH ROW
    EXECUTE FUNCTION update_subjects_updated_at();

-- ============================================
-- TABELA: attendances (Frequências)
-- ============================================
CREATE TABLE attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    timetable_id BIGINT NOT NULL,
    date DATE NOT NULL,
    present BOOLEAN NOT NULL,
    note VARCHAR(255),
    created_by VARCHAR(150),
    last_modified_by VARCHAR(150),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT uk_attendance_unique UNIQUE (student_id, subject_id, date, timetable_id),
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES student(id),
    CONSTRAINT fk_attendance_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT fk_attendance_timetable FOREIGN KEY (timetable_id) REFERENCES timetables(id)
);

-- Índices para otimizar a busca por boletim e diário de classe
CREATE INDEX idx_attendance_student_date ON attendances(student_id, date);
CREATE INDEX idx_attendance_subject_date ON attendances(subject_id, date);

-- Unicidade: impede registrar duas frequências para o mesmo aluno na mesma disciplina e dia
-- ALTER TABLE attendances ADD CONSTRAINT uk_attendance_unique UNIQUE (student_id, subject_id, date);

-- ============================================
-- VIEWS ÚTEIS
-- ============================================

-- View: Notas com detalhes das avaliações
--CREATE VIEW vw_student_grades AS
--SELECT
--    g.id,
--    g.student_user_id,
--    g.assessment_id,
--    a.title as assessment_title,
--    a.due_date,
--    g.score,
--    a.max_score,
--    CASE
--        WHEN g.score IS NOT NULL AND a.max_score > 0
--        THEN ROUND((g.score / a.max_score) * 100, 2)
--        ELSE NULL
--    END as percentage,
--    g.feedback,
--    g.graded_at,
--    s.id as subject_id,
--    s.name as subject_name,
--    s.school_year
--FROM grades g
--JOIN assessments a ON g.assessment_id = a.id
--JOIN subjects s ON a.subject_id = s.id
--WHERE a.is_published = true;
--
---- View: Próximas avaliações
--CREATE VIEW vw_upcoming_assessments AS
--SELECT
--    a.id,
--    a.title,
--    a.due_date,
--    a.subject_id,
--    s.name as subject_name,
--    s.teacher_user_id,
--    COUNT(g.id) as total_students,
--    COUNT(CASE WHEN g.score IS NOT NULL THEN 1 END) as graded_students
--FROM assessments a
--JOIN subjects s ON a.subject_id = s.id
--LEFT JOIN grades g ON a.id = g.assessment_id
--WHERE a.is_published = true
--  AND a.due_date >= CURRENT_DATE
--  AND s.is_active = true
--GROUP BY a.id, a.title, a.due_date, a.subject_id, s.name, s.teacher_user_id;